exclude: 'venv'
fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0 
    hooks:
    - id: check-ast # to check whether files parse as valid python
    - id: check-yaml
    - id: end-of-file-fixer
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.9
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        language_version: python3.9
        args:
          - "."
